name: micro_core
description: A new Flutter package project.
version: 1.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # add the generator to your dev_dependencies
  injectable_generator: ^2.1.0
  # add build runner if not already added
  build_runner: ^2.3.3

flutter:
